### ISSUE TITLE
spring-cloud-kubernetes-discoveryserver is need to deploy ?

### ISSUE THREAD

**Issue by czy006** [ameizi/spring-cloud-kubernetes-samples#1]
spring-cloud-kubernetes-discoveryserver 这个服务我看demo，是必须要部署的，我想问问这个是否能直接用原生k8s 而不用部署这一个服务发现的服务呢，这样就多了一个组件部署比较麻烦. 如果方便可以解答一下吗 感谢

**Comment by v5tech** [comment]
这个组件不是必须的，这里之所以部署是有时候我们可能没有直接访问kubernetes集群的权限，所以借助这个服务去访问kubernetes集群中的服务。真正生产环境这个服务是不需要的。具体可以参考https://spring.io/blog/2021/10/26/new-features-for-spring-cloud-kubernetes-in-spring-cloud-2021-0-0-m3 @czy006

**Comment by czy006** [comment]
嗯嗯 好的 感谢
